"""
Seed script for validated psychological instruments.
Run: python seed_instruments.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from dotenv import load_dotenv
load_dotenv()

from app.database import SessionLocal
from app.models.instrument import Instrument

INSTRUMENTS = [
    {
        "name": "Generalized Anxiety Disorder 7-item Scale",
        "abbreviation": "GAD-7",
        "construct": "Generalized Anxiety",
        "description": "A 7-item self-report scale for screening and measuring severity of generalized anxiety disorder. Widely used in clinical and research settings.",
        "num_items": 7,
        "response_format": "4-point Likert (0=Not at all, 3=Nearly every day)",
        "is_validated": True,
        "apa_ref": "Spitzer, R. L., Kroenke, K., Williams, J. B. W., & Löwe, B. (2006). A brief measure for assessing generalized anxiety disorder. Archives of Internal Medicine, 166(10), 1092–1097. https://doi.org/10.1001/archinte.166.10.1092",
        "items_json": [
            {"id": 1, "text": "Feeling nervous, anxious, or on edge"},
            {"id": 2, "text": "Not being able to stop or control worrying"},
            {"id": 3, "text": "Worrying too much about different things"},
            {"id": 4, "text": "Trouble relaxing"},
            {"id": 5, "text": "Being so restless that it is hard to sit still"},
            {"id": 6, "text": "Becoming easily annoyed or irritable"},
            {"id": 7, "text": "Feeling afraid, as if something awful might happen"},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [0, 21],
            "cutoffs": {"minimal": [0, 4], "mild": [5, 9], "moderate": [10, 14], "severe": [15, 21]},
            "reverse_items": [],
            "note": "Sum all items. Scores ≥10 suggest clinically significant anxiety.",
        },
    },
    {
        "name": "Patient Health Questionnaire-9",
        "abbreviation": "PHQ-9",
        "construct": "Depression",
        "description": "A 9-item self-administered version of the PRIME-MD diagnostic instrument for depression. The criterion standard for depression screening in research.",
        "num_items": 9,
        "response_format": "4-point Likert (0=Not at all, 3=Nearly every day)",
        "is_validated": True,
        "apa_ref": "Kroenke, K., Spitzer, R. L., & Williams, J. B. W. (2001). The PHQ-9: Validity of a brief depression severity measure. Journal of General Internal Medicine, 16(9), 606–613. https://doi.org/10.1046/j.1525-1497.2001.016009606.x",
        "items_json": [
            {"id": 1, "text": "Little interest or pleasure in doing things"},
            {"id": 2, "text": "Feeling down, depressed, or hopeless"},
            {"id": 3, "text": "Trouble falling or staying asleep, or sleeping too much"},
            {"id": 4, "text": "Feeling tired or having little energy"},
            {"id": 5, "text": "Poor appetite or overeating"},
            {"id": 6, "text": "Feeling bad about yourself — or that you are a failure or have let yourself or your family down"},
            {"id": 7, "text": "Trouble concentrating on things, such as reading the newspaper or watching television"},
            {"id": 8, "text": "Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual"},
            {"id": 9, "text": "Thoughts that you would be better off dead, or of hurting yourself in some way"},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [0, 27],
            "cutoffs": {"minimal": [0, 4], "mild": [5, 9], "moderate": [10, 14], "moderately_severe": [15, 19], "severe": [20, 27]},
            "reverse_items": [],
            "note": "Sum all items. Scores ≥10 suggest clinically significant depression.",
        },
    },
    {
        "name": "Rosenberg Self-Esteem Scale",
        "abbreviation": "RSES",
        "construct": "Self-Esteem",
        "description": "A 10-item scale measuring global self-esteem using a 4-point response format. The most widely used self-esteem measure in social science research.",
        "num_items": 10,
        "response_format": "4-point Likert (1=Strongly Agree, 4=Strongly Disagree)",
        "is_validated": True,
        "apa_ref": "Rosenberg, M. (1965). Society and the adolescent self-image. Princeton University Press.",
        "items_json": [
            {"id": 1, "text": "I feel that I am a person of worth, at least on an equal plane with others"},
            {"id": 2, "text": "I feel that I have a number of good qualities"},
            {"id": 3, "text": "All in all, I am inclined to feel that I am a failure", "reverse": True},
            {"id": 4, "text": "I am able to do things as well as most other people"},
            {"id": 5, "text": "I feel I do not have much to be proud of", "reverse": True},
            {"id": 6, "text": "I take a positive attitude toward myself"},
            {"id": 7, "text": "On the whole, I am satisfied with myself"},
            {"id": 8, "text": "I wish I could have more respect for myself", "reverse": True},
            {"id": 9, "text": "I certainly feel useless at times", "reverse": True},
            {"id": 10, "text": "At times I think I am no good at all", "reverse": True},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [10, 40],
            "reverse_items": [3, 5, 8, 9, 10],
            "note": "Reverse-score items 3, 5, 8, 9, 10 (1→4, 2→3, 3→2, 4→1), then sum. Higher scores = higher self-esteem. Scores below 15 suggest low self-esteem.",
        },
    },
    {
        "name": "Perceived Stress Scale",
        "abbreviation": "PSS-10",
        "construct": "Perceived Stress",
        "description": "A 10-item psychological instrument for measuring the perception of stress. Assesses the degree to which situations in life are appraised as stressful.",
        "num_items": 10,
        "response_format": "5-point Likert (0=Never, 4=Very often)",
        "is_validated": True,
        "apa_ref": "Cohen, S., Kamarck, T., & Mermelstein, R. (1983). A global measure of perceived stress. Journal of Health and Social Behavior, 24(4), 385–396. https://doi.org/10.2307/2136404",
        "items_json": [
            {"id": 1, "text": "In the last month, how often have you been upset because of something that happened unexpectedly?"},
            {"id": 2, "text": "In the last month, how often have you felt that you were unable to control the important things in your life?"},
            {"id": 3, "text": "In the last month, how often have you felt nervous and stressed?"},
            {"id": 4, "text": "In the last month, how often have you felt confident about your ability to handle your personal problems?", "reverse": True},
            {"id": 5, "text": "In the last month, how often have you felt that things were going your way?", "reverse": True},
            {"id": 6, "text": "In the last month, how often have you been able to control irritations in your life?", "reverse": True},
            {"id": 7, "text": "In the last month, how often have you felt that you were on top of things?", "reverse": True},
            {"id": 8, "text": "In the last month, how often have you been angered because of things that happened that were outside of your control?"},
            {"id": 9, "text": "In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?"},
            {"id": 10, "text": "In the last month, how often have you been able to control the way you spend your time?", "reverse": True},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [0, 40],
            "reverse_items": [4, 5, 6, 7, 10],
            "cutoffs": {"low": [0, 13], "moderate": [14, 26], "high": [27, 40]},
            "note": "Reverse-score items 4, 5, 6, 7, 10, then sum. Higher scores = more perceived stress.",
        },
    },
    {
        "name": "UCLA Loneliness Scale (Version 3)",
        "abbreviation": "UCLA-LS",
        "construct": "Loneliness",
        "description": "A 20-item scale designed to measure subjective feelings of loneliness and social isolation. Version 3 is the most widely used form.",
        "num_items": 20,
        "response_format": "4-point Likert (1=Never, 4=Often)",
        "is_validated": True,
        "apa_ref": "Russell, D. W. (1996). UCLA Loneliness Scale (Version 3): Reliability, validity, and factor structure. Journal of Personality Assessment, 66(1), 20–40. https://doi.org/10.1207/s15327752jpa6601_2",
        "items_json": [
            {"id": 1, "text": "How often do you feel that you are 'in tune' with the people around you?", "reverse": True},
            {"id": 2, "text": "How often do you feel that you lack companionship?"},
            {"id": 3, "text": "How often do you feel that there is no one you can turn to?"},
            {"id": 4, "text": "How often do you feel alone?"},
            {"id": 5, "text": "How often do you feel part of a group of friends?", "reverse": True},
            {"id": 6, "text": "How often do you feel that you have a lot in common with the people around you?", "reverse": True},
            {"id": 7, "text": "How often do you feel that you are no longer close to anyone?"},
            {"id": 8, "text": "How often do you feel that your interests and ideas are not shared by those around you?"},
            {"id": 9, "text": "How often do you feel outgoing and friendly?", "reverse": True},
            {"id": 10, "text": "How often do you feel close to people?", "reverse": True},
            {"id": 11, "text": "How often do you feel left out?"},
            {"id": 12, "text": "How often do you feel that your relationships with others are not meaningful?"},
            {"id": 13, "text": "How often do you feel that no one really knows you well?"},
            {"id": 14, "text": "How often do you feel isolated from others?"},
            {"id": 15, "text": "How often do you feel you can find companionship when you want it?", "reverse": True},
            {"id": 16, "text": "How often do you feel that there are people who really understand you?", "reverse": True},
            {"id": 17, "text": "How often do you feel shy?"},
            {"id": 18, "text": "How often do you feel that people are around you but not with you?"},
            {"id": 19, "text": "How often do you feel that there are people you can talk to?", "reverse": True},
            {"id": 20, "text": "How often do you feel that there are people you can turn to?", "reverse": True},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [20, 80],
            "reverse_items": [1, 5, 6, 9, 10, 15, 16, 19, 20],
            "note": "Reverse-score the designated items (1→4, 2→3, 3→2, 4→1), then sum. Higher = more loneliness. Mean score in general population ≈ 40.",
        },
    },
    {
        "name": "Big Five Inventory",
        "abbreviation": "BFI-44",
        "construct": "Big Five Personality Traits",
        "description": "A 44-item inventory measuring the Big Five personality dimensions: Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism (OCEAN).",
        "num_items": 44,
        "response_format": "5-point Likert (1=Disagree strongly, 5=Agree strongly)",
        "is_validated": True,
        "apa_ref": "John, O. P., Naumann, L. P., & Soto, C. J. (2008). Paradigm shift to the integrative Big Five taxonomy. In O. P. John, R. W. Robins, & L. A. Pervin (Eds.), Handbook of personality: Theory and research (pp. 114–158). Guilford Press.",
        "items_json": [
            {"id": 1, "text": "I see myself as someone who is talkative", "subscale": "Extraversion"},
            {"id": 2, "text": "I see myself as someone who tends to find fault with others", "subscale": "Agreeableness", "reverse": True},
            {"id": 3, "text": "I see myself as someone who does a thorough job", "subscale": "Conscientiousness"},
            {"id": 4, "text": "I see myself as someone who is depressed, blue", "subscale": "Neuroticism"},
            {"id": 5, "text": "I see myself as someone who is original, comes up with new ideas", "subscale": "Openness"},
            {"id": 6, "text": "I see myself as someone who is reserved", "subscale": "Extraversion", "reverse": True},
            {"id": 7, "text": "I see myself as someone who is helpful and unselfish with others", "subscale": "Agreeableness"},
            {"id": 8, "text": "I see myself as someone who can be somewhat careless", "subscale": "Conscientiousness", "reverse": True},
            {"id": 9, "text": "I see myself as someone who is relaxed, handles stress well", "subscale": "Neuroticism", "reverse": True},
            {"id": 10, "text": "I see myself as someone who is curious about many different things", "subscale": "Openness"},
        ],
        "scoring_json": {
            "method": "subscale_mean",
            "subscales": {
                "Extraversion": {"items": [1, 6, 11, 16, 21, 26, 31, 36], "reverse": [6, 21, 31]},
                "Agreeableness": {"items": [2, 7, 12, 17, 22, 27, 32, 37, 42], "reverse": [2, 12, 27, 37]},
                "Conscientiousness": {"items": [3, 8, 13, 18, 23, 28, 33, 38, 43], "reverse": [8, 18, 23, 43]},
                "Neuroticism": {"items": [4, 9, 14, 19, 24, 29, 34, 39], "reverse": [9, 24, 34]},
                "Openness": {"items": [5, 10, 15, 20, 25, 30, 35, 40, 41, 44], "reverse": [35, 41]},
            },
            "note": "Full 44-item version. Only first 10 items stored here for brevity; use full BFI item list in production.",
        },
    },
    {
        "name": "Satisfaction With Life Scale",
        "abbreviation": "SWLS",
        "construct": "Life Satisfaction / Subjective Well-Being",
        "description": "A 5-item scale designed to measure global cognitive judgments of satisfaction with one's life. Part of the tripartite model of subjective well-being.",
        "num_items": 5,
        "response_format": "7-point Likert (1=Strongly Disagree, 7=Strongly Agree)",
        "is_validated": True,
        "apa_ref": "Diener, E., Emmons, R. A., Larsen, R. J., & Griffin, S. (1985). The Satisfaction with Life Scale. Journal of Personality Assessment, 49(1), 71–75. https://doi.org/10.1207/s15327752jpa4901_13",
        "items_json": [
            {"id": 1, "text": "In most ways my life is close to my ideal"},
            {"id": 2, "text": "The conditions of my life are excellent"},
            {"id": 3, "text": "I am satisfied with my life"},
            {"id": 4, "text": "So far I have gotten the important things I want in life"},
            {"id": 5, "text": "If I could live my life over, I would change almost nothing"},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [5, 35],
            "cutoffs": {
                "extremely_dissatisfied": [5, 9],
                "dissatisfied": [10, 14],
                "slightly_below_average": [15, 19],
                "average": [20, 24],
                "high": [25, 29],
                "very_high": [30, 35],
            },
            "reverse_items": [],
            "note": "Sum all 5 items. Score of 20 represents neutral; 25+ indicates satisfaction above average.",
        },
    },
    {
        "name": "PTSD Checklist for DSM-5",
        "abbreviation": "PCL-5",
        "construct": "PTSD Symptoms",
        "description": "A 20-item self-report measure assessing DSM-5 symptoms of PTSD. Includes four symptom clusters: intrusion, avoidance, negative alterations in cognition/mood, and alterations in arousal/reactivity.",
        "num_items": 20,
        "response_format": "5-point Likert (0=Not at all, 4=Extremely)",
        "is_validated": True,
        "apa_ref": "Blevins, C. A., Weathers, F. W., Davis, M. T., Witte, T. K., & Domino, J. L. (2015). The Posttraumatic Stress Disorder Checklist for DSM-5 (PCL-5): Development and initial psychometric evaluation. Journal of Traumatic Stress, 28(6), 489–498. https://doi.org/10.1002/jts.22059",
        "items_json": [
            {"id": 1, "text": "Repeated, disturbing, and unwanted memories of the stressful experience?", "subscale": "Intrusion"},
            {"id": 2, "text": "Repeated, disturbing dreams of the stressful experience?", "subscale": "Intrusion"},
            {"id": 3, "text": "Suddenly feeling or acting as if the stressful experience were actually happening again (as if you were actually back there reliving it)?", "subscale": "Intrusion"},
            {"id": 4, "text": "Feeling very upset when something reminded you of the stressful experience?", "subscale": "Intrusion"},
            {"id": 5, "text": "Having strong physical reactions when something reminded you of the stressful experience?", "subscale": "Intrusion"},
            {"id": 6, "text": "Avoiding memories, thoughts, or feelings related to the stressful experience?", "subscale": "Avoidance"},
            {"id": 7, "text": "Avoiding external reminders of the stressful experience?", "subscale": "Avoidance"},
            {"id": 8, "text": "Trouble remembering important parts of the stressful experience?", "subscale": "NACM"},
            {"id": 9, "text": "Having strong negative beliefs about yourself, other people, or the world?", "subscale": "NACM"},
            {"id": 10, "text": "Blaming yourself or someone else for the stressful experience or what happened after it?", "subscale": "NACM"},
            {"id": 11, "text": "Having strong negative feelings such as fear, horror, anger, guilt, or shame?", "subscale": "NACM"},
            {"id": 12, "text": "Loss of interest in activities that you used to enjoy?", "subscale": "NACM"},
            {"id": 13, "text": "Feeling distant or cut off from other people?", "subscale": "NACM"},
            {"id": 14, "text": "Trouble experiencing positive feelings?", "subscale": "NACM"},
            {"id": 15, "text": "Irritable behavior, angry outbursts, or acting aggressively?", "subscale": "AAR"},
            {"id": 16, "text": "Taking too many risks or doing things that could cause you harm?", "subscale": "AAR"},
            {"id": 17, "text": "Being 'superalert' or watchful or on guard?", "subscale": "AAR"},
            {"id": 18, "text": "Feeling jumpy or easily startled?", "subscale": "AAR"},
            {"id": 19, "text": "Having difficulty concentrating?", "subscale": "AAR"},
            {"id": 20, "text": "Trouble falling or staying asleep?", "subscale": "AAR"},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [0, 80],
            "cutoffs": {"probable_ptsd": 31},
            "subscales": {
                "Intrusion": [1, 2, 3, 4, 5],
                "Avoidance": [6, 7],
                "NACM": [8, 9, 10, 11, 12, 13, 14],
                "AAR": [15, 16, 17, 18, 19, 20],
            },
            "reverse_items": [],
            "note": "Sum all items. Score ≥31 suggests probable PTSD. Report total and subscale scores.",
        },
    },
    {
        "name": "Mindful Attention Awareness Scale",
        "abbreviation": "MAAS",
        "construct": "Trait Mindfulness",
        "description": "A 15-item scale assessing individual differences in the frequency of mindful states over time — being attentive to and aware of present-moment experience.",
        "num_items": 15,
        "response_format": "6-point Likert (1=Almost always, 6=Almost never)",
        "is_validated": True,
        "apa_ref": "Brown, K. W., & Ryan, R. M. (2003). The benefits of being present: Mindfulness and its role in psychological well-being. Journal of Personality and Social Psychology, 84(4), 822–848. https://doi.org/10.1037/0022-3514.84.4.822",
        "items_json": [
            {"id": 1, "text": "I could be experiencing some emotion and not be conscious of it until some time later"},
            {"id": 2, "text": "I break or spill things because of carelessness, not paying attention, or thinking of something else"},
            {"id": 3, "text": "I find it difficult to stay focused on what's happening in the present"},
            {"id": 4, "text": "I tend to walk quickly to get where I'm going without paying attention to what I experience along the way"},
            {"id": 5, "text": "I tend not to notice feelings of physical tension or discomfort until they really grab my attention"},
            {"id": 6, "text": "I forget a person's name almost as soon as I've been told it for the first time"},
            {"id": 7, "text": "It seems I am 'running on automatic,' without much awareness of what I'm doing"},
            {"id": 8, "text": "I rush through activities without being really attentive to them"},
            {"id": 9, "text": "I get so focused on the goal I want to achieve that I lose touch with what I'm doing right now to get there"},
            {"id": 10, "text": "I do jobs or tasks automatically, without being aware of what I'm doing"},
            {"id": 11, "text": "I find myself listening to someone with one ear, doing something else at the same time"},
            {"id": 12, "text": "I drive places on 'automatic pilot' and then wonder why I went there"},
            {"id": 13, "text": "I find myself preoccupied with the future or the past"},
            {"id": 14, "text": "I find myself doing things without paying attention"},
            {"id": 15, "text": "I snack without being aware that I'm eating"},
        ],
        "scoring_json": {
            "method": "mean",
            "range": [1, 6],
            "reverse_items": [],
            "note": "Calculate mean of all 15 items. Higher scores = greater mindfulness. No reverse scoring needed — all items are already phrased in the low-mindfulness direction.",
        },
    },
    {
        "name": "State-Trait Anxiety Inventory (Short Form)",
        "abbreviation": "STAI-6",
        "construct": "State Anxiety",
        "description": "A 6-item short form of the STAI for measuring state anxiety. Validated for research contexts where brevity is required. Correlates highly (r > .90) with the full STAI.",
        "num_items": 6,
        "response_format": "4-point Likert (1=Not at all, 4=Very much so)",
        "is_validated": True,
        "apa_ref": "Marteau, T. M., & Bekker, H. (1992). The development of a six-item short-form of the state scale of the Spielberger State-Trait Anxiety Inventory (STAI). British Journal of Clinical Psychology, 31(3), 301–306. https://doi.org/10.1111/j.2044-8260.1992.tb00997.x",
        "items_json": [
            {"id": 1, "text": "I feel calm", "reverse": True},
            {"id": 2, "text": "I feel tense"},
            {"id": 3, "text": "I feel upset"},
            {"id": 4, "text": "I feel relaxed", "reverse": True},
            {"id": 5, "text": "I feel content", "reverse": True},
            {"id": 6, "text": "I am worried"},
        ],
        "scoring_json": {
            "method": "mean",
            "range": [1, 4],
            "reverse_items": [1, 4, 5],
            "note": "Reverse-score items 1, 4, 5 (1→4, 2→3, 3→2, 4→1), then calculate mean. Multiply by 20/3 to convert to 0–80 scale comparable to full STAI.",
        },
    },
    {
        "name": "Beck Depression Inventory-II",
        "abbreviation": "BDI-II",
        "construct": "Depression Severity",
        "description": "A 21-item self-report instrument for measuring the severity of depression. Aligned with DSM-IV criteria for major depressive disorder.",
        "num_items": 21,
        "response_format": "4-point scale (0–3 per item, grouped statements)",
        "is_validated": True,
        "apa_ref": "Beck, A. T., Steer, R. A., & Brown, G. K. (1996). Manual for the Beck Depression Inventory-II. Psychological Corporation.",
        "items_json": [
            {"id": 1, "text": "Sadness (0=I do not feel sad, 3=I am so sad or unhappy that I can't stand it)"},
            {"id": 2, "text": "Pessimism (0=I am not discouraged about my future, 3=I feel my future is hopeless and will only get worse)"},
            {"id": 3, "text": "Past Failure (0=I do not feel like a failure, 3=I feel I am a total failure as a person)"},
            {"id": 4, "text": "Loss of Pleasure (0=I get as much pleasure as I ever did from things, 3=I can't get any satisfaction from the things I used to enjoy)"},
            {"id": 5, "text": "Guilty Feelings (0=I don't feel particularly guilty, 3=I feel guilty all of the time)"},
            {"id": 6, "text": "Punishment Feelings (0=I don't feel I am being punished, 3=I feel I am being punished)"},
            {"id": 7, "text": "Self-Dislike (0=I feel the same way about myself as ever, 3=I dislike myself)"},
            {"id": 8, "text": "Self-Criticalness (0=I don't criticize or blame myself more than usual, 3=I blame myself for everything bad that happens)"},
            {"id": 9, "text": "Suicidal Thoughts (0=I don't have any thoughts of killing myself, 3=I would kill myself if I had the chance)"},
            {"id": 10, "text": "Crying (0=I don't cry any more than I used to, 3=I feel like crying but I can't)"},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [0, 63],
            "cutoffs": {"minimal": [0, 13], "mild": [14, 19], "moderate": [20, 28], "severe": [29, 63]},
            "reverse_items": [],
            "note": "Sum all 21 items (each 0–3). Only first 10 items stored here. Requires licensed administration in clinical settings.",
        },
    },
    {
        "name": "Impact of Event Scale-Revised",
        "abbreviation": "IES-R",
        "construct": "Trauma-Related Distress",
        "description": "A 22-item self-report measure of subjective distress caused by traumatic events. Measures intrusion, avoidance, and hyperarousal.",
        "num_items": 22,
        "response_format": "5-point Likert (0=Not at all, 4=Extremely)",
        "is_validated": True,
        "apa_ref": "Weiss, D. S., & Marmar, C. R. (1997). The Impact of Event Scale-Revised. In J. P. Wilson & T. M. Keane (Eds.), Assessing psychological trauma and PTSD (pp. 399–411). Guilford Press.",
        "items_json": [
            {"id": 1, "text": "Any reminder brought back feelings about it", "subscale": "Intrusion"},
            {"id": 2, "text": "I had trouble staying asleep", "subscale": "Hyperarousal"},
            {"id": 3, "text": "Other things kept making me think about it", "subscale": "Intrusion"},
            {"id": 4, "text": "I felt irritable and angry", "subscale": "Hyperarousal"},
            {"id": 5, "text": "I avoided letting myself get upset when I thought about it or was reminded of it", "subscale": "Avoidance"},
            {"id": 6, "text": "I thought about it when I didn't mean to", "subscale": "Intrusion"},
            {"id": 7, "text": "I felt as if it hadn't happened or wasn't real", "subscale": "Avoidance"},
            {"id": 8, "text": "I stayed away from reminders about it", "subscale": "Avoidance"},
            {"id": 9, "text": "Pictures about it popped into my mind", "subscale": "Intrusion"},
            {"id": 10, "text": "I was jumpy and easily startled", "subscale": "Hyperarousal"},
        ],
        "scoring_json": {
            "method": "subscale_sum",
            "subscales": {"Intrusion": [1, 3, 6, 9, 16, 20, 22], "Avoidance": [5, 7, 8, 11, 12, 13, 17, 22], "Hyperarousal": [2, 4, 10, 14, 15, 18, 19]},
            "cutoffs": {"partial_ptsd": 24, "probable_ptsd": 33, "best_cutoff": 22},
            "reverse_items": [],
            "note": "Sum scores within each subscale. Total score ≥33 suggests probable PTSD.",
        },
    },
    {
        "name": "Interpersonal Reactivity Index",
        "abbreviation": "IRI",
        "construct": "Empathy",
        "description": "A 28-item multidimensional measure of empathy assessing four constructs: perspective taking, fantasy, empathic concern, and personal distress.",
        "num_items": 28,
        "response_format": "5-point Likert (0=Does not describe me well, 4=Describes me very well)",
        "is_validated": True,
        "apa_ref": "Davis, M. H. (1983). Measuring individual differences in empathy: Evidence for a multidimensional approach. Journal of Personality and Social Psychology, 44(1), 113–126. https://doi.org/10.1037/0022-3514.44.1.113",
        "items_json": [
            {"id": 1, "text": "I daydream and fantasize, with some regularity, about things that might happen to me", "subscale": "Fantasy"},
            {"id": 2, "text": "I often have tender, concerned feelings for people less fortunate than me", "subscale": "Empathic Concern"},
            {"id": 3, "text": "I sometimes find it difficult to see things from the 'other guy's' point of view", "subscale": "Perspective Taking", "reverse": True},
            {"id": 4, "text": "Sometimes I don't feel very sorry for other people when they are having problems", "subscale": "Empathic Concern", "reverse": True},
            {"id": 5, "text": "I really get involved with the feelings of the characters in a novel", "subscale": "Fantasy"},
            {"id": 6, "text": "In emergency situations, I feel apprehensive and ill-at-ease", "subscale": "Personal Distress"},
            {"id": 7, "text": "I am usually objective when I watch a movie or play, and I don't often get completely caught up in it", "subscale": "Fantasy", "reverse": True},
        ],
        "scoring_json": {
            "method": "subscale_mean",
            "subscales": {
                "Perspective Taking": {"items": [3, 8, 11, 15, 21, 25, 28], "reverse": [3]},
                "Fantasy": {"items": [1, 5, 7, 12, 16, 23, 26], "reverse": [7]},
                "Empathic Concern": {"items": [2, 4, 9, 14, 18, 20, 22], "reverse": [4]},
                "Personal Distress": {"items": [6, 10, 13, 17, 19, 24, 27], "reverse": []},
            },
            "reverse_items": [3, 4, 7, 12, 13, 14, 15, 19],
            "note": "Only first 7 items stored here. Score each subscale separately; no total score recommended.",
        },
    },
    {
        "name": "Social Phobia Inventory",
        "abbreviation": "SPIN",
        "construct": "Social Anxiety Disorder",
        "description": "A 17-item self-rated instrument for measuring fear, avoidance, and physiological discomfort associated with social anxiety disorder.",
        "num_items": 17,
        "response_format": "5-point Likert (0=Not at all, 4=Extremely)",
        "is_validated": True,
        "apa_ref": "Connor, K. M., Davidson, J. R. T., Churchill, L. E., Sherwood, A., Foa, E., & Weisler, R. H. (2000). Psychometric properties of the Social Phobia Inventory (SPIN). British Journal of Psychiatry, 176(4), 379–386. https://doi.org/10.1192/bjp.176.4.379",
        "items_json": [
            {"id": 1, "text": "I am afraid of people in authority", "subscale": "Fear"},
            {"id": 2, "text": "I am bothered by blushing in front of people", "subscale": "Physiological"},
            {"id": 3, "text": "Parties and social events scare me", "subscale": "Fear"},
            {"id": 4, "text": "I avoid talking to people I don't know", "subscale": "Avoidance"},
            {"id": 5, "text": "Being criticized scares me a lot", "subscale": "Fear"},
            {"id": 6, "text": "I avoid doing things or speaking to people for fear of embarrassment", "subscale": "Avoidance"},
            {"id": 7, "text": "Sweating in front of people causes me distress", "subscale": "Physiological"},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [0, 68],
            "cutoffs": {"no_sad": [0, 18], "mild": [19, 29], "moderate": [30, 39], "severe": [40, 49], "very_severe": [50, 68]},
            "subscales": {"Fear": [1, 3, 5, 9, 13, 17], "Avoidance": [4, 6, 8, 10, 12, 14, 16], "Physiological": [2, 7, 11, 15]},
            "reverse_items": [],
            "note": "Sum all 17 items. Cutoff of ≥19 indicates probable Social Anxiety Disorder.",
        },
    },
    {
        "name": "General Self-Efficacy Scale",
        "abbreviation": "GSE",
        "construct": "Self-Efficacy",
        "description": "A 10-item psychometric scale that assesses optimistic self-beliefs to cope with a variety of difficult demands in life.",
        "num_items": 10,
        "response_format": "4-point Likert (1=Not at all true, 4=Exactly true)",
        "is_validated": True,
        "apa_ref": "Schwarzer, R., & Jerusalem, M. (1995). Generalized Self-Efficacy scale. In J. Weinman, S. Wright, & M. Johnston (Eds.), Measures in health psychology: A user's portfolio (pp. 35–37). NFER-NELSON.",
        "items_json": [
            {"id": 1, "text": "I can always manage to solve difficult problems if I try hard enough"},
            {"id": 2, "text": "If someone opposes me, I can find the means and ways to get what I want"},
            {"id": 3, "text": "It is easy for me to stick to my aims and accomplish my goals"},
            {"id": 4, "text": "I am confident that I could deal efficiently with unexpected events"},
            {"id": 5, "text": "Thanks to my resourcefulness, I know how to handle unforeseen situations"},
            {"id": 6, "text": "I can solve most problems if I invest the necessary effort"},
            {"id": 7, "text": "I can remain calm when facing difficulties because I can rely on my coping abilities"},
            {"id": 8, "text": "When I am confronted with a problem, I can usually find several solutions"},
            {"id": 9, "text": "If I am in trouble, I can usually think of a solution"},
            {"id": 10, "text": "I can usually handle whatever comes my way"},
        ],
        "scoring_json": {
            "method": "sum",
            "range": [10, 40],
            "reverse_items": [],
            "note": "Sum all 10 items. Higher scores indicate stronger belief in one's competence to handle difficult situations.",
        },
    },
]


def seed():
    db = SessionLocal()
    try:
        existing = db.query(Instrument).count()
        if existing > 0:
            print(f"Already have {existing} instruments. Skipping seed.")
            return

        for data in INSTRUMENTS:
            instrument = Instrument(**data)
            db.add(instrument)

        db.commit()
        print(f"✓ Seeded {len(INSTRUMENTS)} validated instruments.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
